### ISSUE TITLE
Main menu is cramped

### ISSUE THREAD

**Issue by spaanse** [EmilRiedeman/CodeCup-Spaghetti-Java-GUI#1]
See image below:
![image](https://user-images.githubusercontent.com/19549928/126911189-50b18323-b62e-416b-bd5c-d3578ab3584b.png)

OS: Ubuntu 20.04
Java: openjdk 11.0.11 2021-04-20

**Comment by EmilRiedeman** [comment]
`import javax.swing.*;

public class FontSizeTest {
    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        JTextField textField = new JTextField("test");
        System.out.println(textField.getFont().getSize());
    }
}
`
Kan je dit runnen en dan doorgeven wat het output? Als ik het op Windows run krijg ik 11 en met WSL krijg ik 12. Alvast bedankt.

**Comment by EmilRiedeman** [comment]
Kan je het volgende compilen met javac en dan runnen en doorgeven wat het output? Alvast bedankt. (eerst omzetten naar "FontSizeTest.java")
[FontSizeTest.txt](https://github.com/EmilRiedeman/CodeCup-Spaghetti-Java-GUI/files/6874566/FontSizeTest.txt)

**Comment by spaanse** [comment]
```
15
```

**Comment by EmilRiedeman** [comment]
[spaghetti.txt](https://github.com/EmilRiedeman/CodeCup-Spaghetti-Java-GUI/files/6877349/spaghetti.txt)
Is het probleem gefixt in deze versie?

**Comment by spaanse** [comment]
![image](https://user-images.githubusercontent.com/19549928/127471839-766d83ef-1e17-4398-87bb-4eba12aa0afd.png)
Nope

**Comment by EmilRiedeman** [comment]
Ludo heeft deze issue opgelost. Ik heb een nieuwe release gedaan, waar het nu wel hoort te werken.

**Comment by spaanse** [comment]
Ziet er wel wat beter uit, alleen op het speelscherm moet je nog iets meer ruimte onder geven
![Screenshot from 2021-08-15 10-39-58](https://user-images.githubusercontent.com/19549928/129472499-2efdef48-ae2f-4e78-816b-8db6b81b920b.png)
